//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_SharedResource_fa_IR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_SharedResource_fa_IR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Resources.SharedResource.fa-IR", typeof(Resources_SharedResource_fa_IR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراخوان پیدا نشد.
        /// </summary>
        internal static string AnnouncementNotFound {
            get {
                return ResourceManager.GetString("AnnouncementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جواب نظر سنجی یافت نشد.
        /// </summary>
        internal static string AnswerNotFound {
            get {
                return ResourceManager.GetString("AnswerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رویداد درسی پیدا نشد.
        /// </summary>
        internal static string CourseEventNotFound {
            get {
                return ResourceManager.GetString("CourseEventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درس مورد نظر پیدا نشد.
        /// </summary>
        internal static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان درس موجود نمی باشد.
        /// </summary>
        internal static string CourseTypeNotFound {
            get {
                return ResourceManager.GetString("CourseTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد آموزشی یافت نشد.
        /// </summary>
        internal static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید نباید تکراری باشد.
        /// </summary>
        internal static string DuplicatePassword {
            get {
                return ResourceManager.GetString("DuplicatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربر تکراری است.
        /// </summary>
        internal static string DuplicateUser {
            get {
                return ResourceManager.GetString("DuplicateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل پیدا نشد.
        /// </summary>
        internal static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سرویس ایمیل.
        /// </summary>
        internal static string EmailServiceException {
            get {
                return ResourceManager.GetString("EmailServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد نباید خالی باشد.
        /// </summary>
        internal static string EmptyInput {
            get {
                return ResourceManager.GetString("EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رویداد یافت نشد.
        /// </summary>
        internal static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علاقه مندی یافت نشد.
        /// </summary>
        internal static string FavouriteNotFound {
            get {
                return ResourceManager.GetString("FavouriteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل مورد نظر یافت نشد.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ضروری است.
        /// </summary>
        internal static string FirstnameRequired {
            get {
                return ResourceManager.GetString("FirstnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استاد یافت نشد.
        /// </summary>
        internal static string InstructorNotFound {
            get {
                return ResourceManager.GetString("InstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل صحیح نیست.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل یا رمز عبور نادرست است.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور نادرست است.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید نادرست است.
        /// </summary>
        internal static string InvalidValidationToken {
            get {
                return ResourceManager.GetString("InvalidValidationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی ضروری است.
        /// </summary>
        internal static string LastnameRequired {
            get {
                return ResourceManager.GetString("LastnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبر یافت نشد.
        /// </summary>
        internal static string NewsNotFound {
            get {
                return ResourceManager.GetString("NewsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعیه یافت نشد.
        /// </summary>
        internal static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگهی یافت نشد.
        /// </summary>
        internal static string OfferNotFound {
            get {
                return ResourceManager.GetString("OfferNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید حداقل 6 کاراکتر باشد.
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور ضروری است.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرسنجی به پایان رسیده است.
        /// </summary>
        internal static string PollIsNotOpen {
            get {
                return ResourceManager.GetString("PollIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال نظرسنجی یافت نشد.
        /// </summary>
        internal static string QuestionNotFound {
            get {
                return ResourceManager.GetString("QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانشجو یافت نشد.
        /// </summary>
        internal static string StudentNotFound {
            get {
                return ResourceManager.GetString("StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجشنبه.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت یافت نشد.
        /// </summary>
        internal static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ها تداخل دارند.
        /// </summary>
        internal static string TimeConflict {
            get {
                return ResourceManager.GetString("TimeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان یافت نشد.
        /// </summary>
        internal static string TimeNotFound {
            get {
                return ResourceManager.GetString("TimeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی مجاز نیست.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی رمز عبور مجاز نیست.
        /// </summary>
        internal static string UnauthorizedResetPassword {
            get {
                return ResourceManager.GetString("UnauthorizedResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید ایمیل مجاز نیست.
        /// </summary>
        internal static string UnautorizedValidation {
            get {
                return ResourceManager.GetString("UnautorizedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای غیر منتظره.
        /// </summary>
        internal static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما یک رخداد درسی جدید دارید.
        /// </summary>
        internal static string YouHaveANewCourseEvent {
            get {
                return ResourceManager.GetString("YouHaveANewCourseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به یک درس جدید اضافه شده اید.
        /// </summary>
        internal static string YouHaveBeenAddedToACourse {
            get {
                return ResourceManager.GetString("YouHaveBeenAddedToACourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت شما مورد بررسی قرار گرفت و مشکل رفع گردید.
        /// </summary>
        internal static string YourTicketHasBeenSolved {
            get {
                return ResourceManager.GetString("YourTicketHasBeenSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت شما درحال بررسی است.
        /// </summary>
        internal static string YourTicketIsInProgress {
            get {
                return ResourceManager.GetString("YourTicketIsInProgress", resourceCulture);
            }
        }
    }
}
