namespace Domain.Enum
{
    public enum ErrorType
    {
        DuplicateUser,
        Unexpected,
        InvalidInput,
        UserNotFound,
        Unauthorized,
        CourseNotFound,
        EmailNotFound,
        CourseEventNotFound,
        UnauthorizedResetPassword,
        UnauthorizedValidation,
        EmailServiceException,
        DuplicatePassword,
        InvalidPassword,
        NewsNotFound,
        PollIsNotOpen,
        FileNotFound,
        EventNotFound,
        InvalidValidationToken,
        AnswerNotFound,
        QuestionNotFound,
        OfferNotFound,
        StudentNotFound,
        TimeConflict,
        TimeNotFound,
        CourseTypeNotFound,
        DepartmentNotFound,
        AnnouncementNotFound,
        InstructorNotFound,
        FavouriteNotFound,
        CommentNotFound
    }
}